baremetal: Add shiftstack dev authorized_keys, add when for squid container
- We need to give access to shiftstack dev to the bm instance for debug
- Ensure we create squid container only if it's not present to avoid:

Error: creating container storage: the container name "squid" is
already in use by ...

Change-Id: I42412b97cba0321c2f453d0d3d0754e1717db6b2