Rename variable for -Xms and -Xmx for OpenSearch rdoproject
The correct variables does not have elasticsearch sufix,
but 'opensearch' [1].
That needs to be done because of the error what we have in logsender:

    Jan 31 20:55:46 elk.softwarefactory-project.io logsender-softwarefactory-project.io[27541]:
    opensearchpy.exceptions.TransportError: TransportError(
        429, 'circuit_breaking_exception',
        '[parent] Data too large, data for [<http_request>] would be [517260008/493.2mb],
        which is larger than the limit of [510027366/486.3mb],
        real usage: [517260008/493.2mb],
        new bytes reserved: [0/0b],
        usages [request=0/0b, fielddata=132392/129.2kb, in_flight_requests=0/0b]'
    )

[1] https://softwarefactory-project.io/r/plugins/gitiles/software-factory/ansible-role-elastic-recheck/+/refs/heads/master/tasks/configure-opensearch.yml#79

Change-Id: Id60bcd7713ad84add5837d305aa4c76ea752d6bf