Switch Logscraper and Logsender image to be based on Centos 8 Stream
In the new Zuul version which is running on the microshift host,
some fields have been changed to be a dict, so it requires to apply
patch [1], but also the ci-log-processing project has moved to use
Centos 9 Stream container images, which does not work on Centos 7 host,
because it will raise an error:

    INFO:root:Processing 4500 builds
    Traceback (most recent call last):
    File "/usr/local/bin/logscraper", line 10, in <module>
    sys.exit(main())
    ^^^^^^
    File "/usr/local/lib/python3.11/site-packages/logscraper/logscraper.py", line 769, in main
    run(args, monitoring)
    File "/usr/local/lib/python3.11/site-packages/logscraper/logscraper.py", line 754, in run
    run_scraping(args, zuul_api_url, monitoring=monitoring)
    File "/usr/local/lib/python3.11/site-packages/logscraper/logscraper.py", line 722, in run_scraping
    pool = multiprocessing.Pool(int(args.workers))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib64/python3.11/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib64/python3.11/multiprocessing/pool.py", line 235, in __init__
    self._worker_handler.start()
    File "/usr/lib64/python3.11/threading.py", line 964, in start
    _start_new_thread(self._bootstrap, ())
    RuntimeError: can't start new thread

The temporary image was done by executing:

    git clone https://opendev.org/openstack/ci-log-processing && cd ci-log-processing
    sed -i 's/stream9/stream8/g' Dockerfile
    podman build -t quay.io/software-factory/logscraper:latest-c8s -f Dockerfile

That is temporary solution until the logscraper and logsender is not
moved to different server which would be running on newer system.

[1] https://review.opendev.org/c/openstack/ci-log-processing/+/911423

Change-Id: Ia57c4592aa744c671b35f3c2b4e735c84c2287b7