Reboot host when storage driver was changed
If the container driver was changed and the host would be not rebooted
and some container images were created, later (when the host will be
rebooted) we will have error:

    $ podman build -t test:latest -f Dockerfile

    WARN[0000] RunRoot is pointing to a path (/run/user/1002/containers) which is not writable. Most likely podman will fail.
    Error: creating events dirs: mkdir /run/user/1002: permission denied

There are few workarounds to fix that [1], but the best way is going
to remove the containers dir and it is how we are going.

[1] https://github.com/containers/podman/issues/5049

Change-Id: I5820ec00ab0d79a84825d008ea16b29bfd82abb6